language: php

php:
  - 5.5
  - 5.6

install:
 - composer install

script:
 - vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 app/controllers/ app/models/ app/library/
